---
- name: Install epel
  when: ansible_os_family == "RedHat"
  yum:
    name: epel-release
    state: latest

- name: Adding Kubernetes repository
  when: ansible_os_family == "RedHat"
  yum_repository:
    name: Kubernetes
    description: Kubernetes repo
    file: kubernetes
    baseurl: http://yum.kubernetes.io/repos/kubernetes-el7-x86_64
    enabled: yes
    gpgcheck: no
  register: kuberepo

- shell: "ls -1 /etc/yum.repos.d"
  when: ansible_os_family == "RedHat"
  register: yum_repos

- name: Use baseurl
  when: ansible_os_family == "RedHat"
  command: "sed -i 's/#baseurl/baseurl/g' /etc/yum.repos.d/{{ item }}"
  with_items: "{{ yum_repos.stdout_lines }}"

- name: Disable mirrors
  when: ansible_os_family == "RedHat"
  command: "sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/{{ item }}"
  with_items: "{{ yum_repos.stdout_lines }}"

- name: Remove mirror fastest mirrors
  when: ansible_os_family == "RedHat"
  file: path=/etc/yum/pluginconf.d/fastestmirror.conf state=absent
